### ISSUE TITLE
Test linear interpolator error

### ISSUE THREAD

**Issue by yukezhu** [StanfordVL/robosuite#82]
`test_linear_interpolator` produced the following error in `v1.0` branch

```
Testing controller EE_IK with trajectory pos and interpolator=linear...
Completed trajectory. Took 30 timesteps total.
Traceback (most recent call last):
  File "test_linear_interpolator.py", line 170, in <module>
    test_linear_interpolator()
  File "test_linear_interpolator.py", line 160, in test_linear_interpolator
    assert timesteps[1] > min_ratio * timesteps[0], "Error: Interpolated trajectory time should be longer " \
AssertionError: Error: Interpolated trajectory time should be longer than non-interpolated!
```

**Comment by cremebrule** [comment]
Resolved!
